#!/usr/bin/env bash

alias run="rs-run"
alias doc="rs-doc"

alias rs-clippy-all="rs-clippy --all-targets --all-features -- -W clippy::all"

alias rustfmt-check="rs-fmt-check"

alias cargo-new-week="cargo new $(date +y%yw%V)"

alias git-pop-head-keep-staged="git reset --soft HEAD~"
alias git-hard-reset-file="git checkout HEAD --"

git-hard-reset-branch-to-origin() {(
    set -e

    branch=$(git branch --show-current)

    git fetch origin
    git reset --hard origin/"$branch"
)}

alias git-diff-word="git diff --color-words"
alias git-diff-char="git diff --color-words=."

alias rs-grep="grep --color=auto --include=\*.rs --exclude-dir={.git,target,node_modules} -rinT . -e"

alias js-grep="grep --color=auto --include=\*.js --exclude-dir={.git,target,node_modules} -rinT . -e"
alias ts-grep="grep --color=auto --include=\*.ts --exclude-dir={.git,target,node_modules} -rinT . -e"

alias css-grep="grep --color=auto --include=\*.css --exclude-dir={.git,target,node_modules} -rinT . -e"
alias scss-grep="grep --color=auto --include=\*.scss --exclude-dir={.git,target,node_modules} -rinT . -e"

alias vscode-edit-dictionary="code $HOME/dictionary.txt"
